mine:
  dimensions:
    side: 10
    height: 5
  
  duration:
    active_time: 40
    warning_time: 20
  
  ore_types:
    - COAL_ORE
    - IRON_ORE
    - GOLD_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    - REDSTONE_ORE
    - LAPIS_ORE
    - COPPER_ORE
  
  limits:
    max_per_player: 1
    max_global: 100

  allowed_worlds: []
  

  auto_regeneration:
    enabled: true
    threshold_percentage: 5
    blocks_per_tick: 5

database:
  type: "mysql"
  mysql:
    host: "localhost"
    port: 3306
    database: "s14_teste3"
    username: "u14_rQYGKQBShY"
    password: "j!2y7=i1cJVGh+mYV3q6!@0o"
  fallback:
    enabled: true
    json_file: "mines.json"
