mine:
  dimensions:
    side: 10
    height: 5
  
  duration:
    active_time: 3600
    warning_time: 300
  
  ore_types:
    - COAL_ORE
    - IRON_ORE
    - GOLD_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    - LAPIS_ORE
    - REDSTONE_ORE
    - COPPER_ORE
    - DEEPSLATE_COAL_ORE
    - DEEPSLATE_IRON_ORE
    - DEEPSLATE_GOLD_ORE
    - DEEPSLATE_DIAMOND_ORE
    - DEEPSLATE_EMERALD_ORE
    - DEEPSLATE_LAPIS_ORE
    - DEEPSLATE_REDSTONE_ORE
    - DEEPSLATE_COPPER_ORE

effects:
  creation:
    sound: ENTITY_ENDER_DRAGON_GROWL
    volume: 1.0
    pitch: 0.5
    particles: PORTAL
    particle_count: 50
  
  expiration:
    sound: ENTITY_GENERIC_EXPLODE
    volume: 0.8
    pitch: 1.0
    particles: EXPLOSION_LARGE
    particle_count: 30
  
  warning:
    sound: BLOCK_NOTE_BLOCK_PLING
    volume: 0.6
    pitch: 2.0
    particles: NOTE
    particle_count: 20
