name: Nyris
version: '1.0-SNAPSHOT'
main: com.morreu.nyris.Nyris
api-version: '1.21'
description: Plugin para criar minas personalizadas
author: Morreu
website: https://github.com/morreu/nyris

commands:
  nyris:
    description: Recebe o item especial da mina, limpa todas as minas ou remove duplicatas
    usage: /nyris [limpar|duplicadas|status|teste|forcar]
    permission: nyris.use

permissions:
  nyris.use:
    description: Permite usar o comando /nyris
    default: true
  nyris.create:
    description: Permite criar minas
    default: true
  nyris.admin:
    description: Permite usar comandos administrativos
    default: op
