name: Nyris
version: '1.0-SNAPSHOT'
main: com.morreu.nyris.Nyris
api-version: '1.21'
description: Plugin para criar minas personalizadas
author: Morreu
website: https://github.com/morreu/nyris

commands:
  nyris:
    description: Recebe o item especial da mina
    usage: /nyris
    permission: nyris.use

permissions:
  nyris.use:
    description: Permite usar o comando /nyris
    default: true
